### ISSUE TITLE
127 error

### ISSUE THREAD

**Issue by CarrieBrown** [CFSAN-Biostatistics/bettercallsal#2]
Hello,

I am trying to get bettercallsaul working on our HPC cluster for one of our clients. I have Nextflow and micromamba set up as described, but I am running into an error that I am at a loss on how to fix. I have attached the 
[nextflow.log](https://github.com/user-attachments/files/17999050/nextflow.log)

```
Dec-03 14:57:04.714 [TaskFinalizer-3] ERROR nextflow.processor.TaskProcessor - Error executing process > 'BETTERCALLSAL:FASTP (cx1AB)'

Caused by:
  Process `BETTERCALLSAL:FASTP (cx1AB)` terminated with an error exit status (127)


Command executed:

  [ ! -f  cx1AB.fastq.gz ] && ln -sf cx1AB.fastq.gz cx1AB.fastq.gz

  fastp \
      --in1 cx1AB.fastq.gz \
      --out1  cx1AB.fastp.fastq.gz \
      --thread 20 \
      --json cx1AB.fastp.json \
      --html cx1AB.fastp.html \
       \
      --dedup  --dup_calc_accuracy 6 --poly_g_min_len 10 -G  --poly_x_min_len 10 --cut_front  --cut_right  --cut_window_size 20 --cut_mean_quality 30 -q 30 -u 40 -n 5 -l 35 -y  -Y 30 -p  -P 20 \
      2> cx1AB.fastp.log

  cat <<-END_VERSIONS > versions.yml
  "BETTERCALLSAL:FASTP":
      fastp: $(fastp --version 2>&1 | sed -e "s/fastp //g")
  END_VERSIONS

Command exit status:
  127

Command output:
  (empty)

Work dir:
  /storage/work/cxb5898/test/work/75/6e7e74e13c1b1cca631942fa1b1621

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
Dec-03 14:57:04.717 [TaskFinalizer-3] DEBUG nextflow.Session - Session aborted -- Cause: Process `BETTERCALLSAL:FASTP (cx1AB)` terminated with an error exit status (127)
```

Please let me know how I can correct this or if there is more information I can provide.

Thank you!

**Comment by biocoder** [comment]
Do you have `your_institution` configured inside [computeinfra.config](../blob/master/conf/computeinfra.config). If not, you can rerun the command using `-profile stdkondagac`, which will run locally without any scheduler. 

If that is not preferred, is your HPC cluster using **SLURM**? If so, add a new config inside the [computeinfra.config](../blob/master/conf/computeinfra.config) with `micromamba` and mention that on the command line.

Example entry inside [computeinfra.config](../blob/master/conf/computeinfra.config):

```bash
texasuniveristywithmicromamba {
    process.executor = 'slurm'
    process.queue = 'prod'
    process.memory = '10GB'
    process.cpus = 4
    singularity.enabled = false
    docker.enabled = false
    params.enable_conda = true
    conda.enabled = true
    conda.useMicromamba = true
    params.enable_module = false
    clusterOptions = '--signal B:USR2'
}
```

Please change `process.queue` to whatever main queue your HPC cluster uses. Now the run with the new profile will be:


Example:

```bash
cpipes \
     --pipeline bettercallsal \
     --input /storage/work/cxb5898/test/bettercallsal_sim_reads \
     --output /storage/work/cxb5898/test/bettercallsal_sim_reads_output \
     --bcs_root_dbdir /storage/work/cxb5898/test/PDG000000002.3082 \
     --kmaalign_ignorequals \ 
     -profile texasuniveristywithmicromamba \
     -resume
```

**Comment by CarrieBrown** [comment]
Yes, I do have a institution specific config entry which contains the following:

```
your_institution {
    process.executer = 'slurm'
    process.queue = 'open'
    singularity.enabled = false
    docker.enabled = false
    conda.enabled = false
    conda.useMicromamaba = true
    params.enable_module = false
}
```

Modifying the above to include process.memory and process.cpus introduced a completely different error:

```
Dec-05 11:03:00.148 [main] ERROR nextflow.cli.Launcher - Unable to parse config file: '/storage/home/cxb5898/bettercallsal/nextflow.config'

  No signature of method: groovy.util.ConfigObject.minus() is applicable for argument types: (String) values: [10GB]
  Possible solutions: minus(java.util.Map), min(groovy.lang.Closure), plus(java.lang.String), find(), find(groovy.lang.Closure), is(java.lang.Object)

groovy.lang.MissingMethodException: No signature of method: groovy.util.ConfigObject.minus() is applicable for argument types: (String) values: [10GB]
```

Any guidance is appreciated.

**Comment by CarrieBrown** [comment]
Updating to add: I tried to run it using the standard local profile specified, and am getting a 'micromamba not found' error even though I can find it in my path:

```
ERROR ~ Error executing process > 'BETTERCALLSAL:PROCESS_FASTQ:GEN_SAMPLESHEET (1)'

Caused by:
  Failed to create Conda environment
    command: micromamba create --yes --quiet --prefix /storage/home/cxb5898/bettercallsal/kondagac_cache/env-a050ae49755c7d5e154ba21c01d4f5f0 conda-forge::python=3.9.5
    status : 127
    message:
      bash: micromamba: command not found



 -- Check '.nextflow.log' file for details

[cxb5898@p-sc-2135 test]$ micromamba
Version: 1.5.9

Usage: /storage/home/cxb5898/bettercallsal/bin/micromamba [OPTIONS] [SUBCOMMAND]

Options:
  -h,--help                   Print this help message and exit
  --version
```

Additionally, could you explain the difference and/or usage of the `params.enable_conda` and `conda.enabled` options in the config?

**Comment by biocoder** [comment]
Both the `params.enable_conda = true` and `conda.enabled = true` are needed in your `your_institution` config. This is due to the fact that the development of this software tool predates many improvements made to `Nextflow` itself on how `conda` virtual environments are activated, due to which this workaround was introduced.

Does your cluster allow job submission from compute nodes? I think the easier way to debug would be to run the main `cpipes` command via submitting it through a batch script (Ex: `sbatch cpipes.sh`). Yeah, it is weird that `micromamba` is not available in your `$PATH` when **Nextflow** is running. May be we can try `echo $PATH` before running the `cpipes` command to confirm `micromamba` availability.

Try using this profile:

```bash
your_institution {
    process.executer = 'slurm'
    process.queue = 'open'
    singularity.enabled = false
    docker.enabled = false
    conda.enabled = true
    params.enable_conda = true
    conda.useMicromamaba = true
    params.enable_module = false
}
```
Your batch job may look like:

```bash
#!/usr/bin/env bash
#SBATCH -c 2
#SBATCH --mem=10g

echo $PATH
which nextflow
which micromamba

cpipes -profile your_institution --input ...... --output ...... 
```

**Comment by CarrieBrown** [comment]
This has been very helpful. Thank you! Our user was able to run his workflow as expected and is not currently having any further issues. We can close this issue.
